name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: purescript-contrib/setup-purescript@main

      - name: Cache PureScript dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.lock') }}
          path: |
            .spago
            output

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: spago build

      - run: spago test
