name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: "24.21.0"
          cache: npm

      - name: Cache PureScript dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: ${{ runner.os }}-${{ runner.arch }}-spago-${{ hashFiles('package-lock.json', 'spago.lock', '**/spago.yaml') }}
          path: |
            .spago
            ~/.cache/spago-nodejs

      - name: Install test dependencies
        run: npm ci

      - name: Build source
        run: npm run build

      - name: Build examples
        run: npm run build:examples

      - name: Build tests
        run: npm run build:test

      - name: Run tests
        run: npm run test

      - name: Bundle examples
        run: npm run bundle:examples

      - name: Build performance bundle
        run: npm run bundle:performance
